### ISSUE TITLE
StalePageException after rerendering a page and then entering values in a typeahead - workaround

### ISSUE THREAD

**Issue by osterberg** [l0rdn1kk0n/wicket-bootstrap#493]
Bloodhound#onBind() seems to cache the url for the BehaviorListener, which leeds to StalePageExceptions after a rerendering of a page.

Reason seems to be: rendercount increases e.g. to 2, but cached url for the BehaviorListener still has 1. 

in the domready-javascript-section i find this part:

"remote":"./page?31-1.IBehaviorListener.0-tabs-panel-AdressdatenPanel-ModalDialog-Form-AdressePanel-Form-AdresseLokal-AdrForm-Strasse&term=%QUERY"

this url "./page?31-1.IBehaviorListener..." doesn't get recalculated, but taken from the cached configuration.

As a quick and dirty workaround, i used following overridden Bloodhound#getConfig():

Bloodhound<String> bloodhound = new Bloodhound<String>(name, cfg)
{
	private static final long	serialVersionUID	= 1L;

	@Override
	public BloodhoundConfig getConfig()
	{
		BloodhoundConfig config = super.getConfig();
		Remote remote = config.getRemote();

		if (remote != null)
		{
		remote.withUrl(getRemoteUrl(remote.getWildcard() != null ? remote.getWildcard() : Remote.DEFAULT_WILDCARD));
		}

		return config;
	}
};

Explanation: getConfig() is called before the js is getting rendered - so i just refreshed the remote url before returning the config.

**Comment by martin-g** [comment]
@pulse00 Ping!

**Comment by pulse00** [comment]
There's not really any deliberate caching going on in [`Bloodhound::onBind()`](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/form/typeaheadV10/bloodhound/Bloodhound.java#L56) - so i assume `onBind` is only called on the first rendering of the page. 

I don't see any apparent side-effects with the proposed solution, so i'd say we could just move the `remoteUrl` configuration into `getConfig` instead of `onBind()`. 

@osterberg i'll check if your workaround introduces any issues here in our applications.

**Comment by osterberg** [comment]
As far as i understand at the moment:

- the url is saved in a Remote object during behavior#onBind().

- behavior#onBind() is called only once for a behavior - in the moment u
add a behavior to a component onBind() is called only once for the lifetime
of a typeahead component on a page.

So there is an unintended caching behavior.


I am not sure if getConfig() is the right place to refresh the remoteUrl,
as getConfig() is called multiple times - even in
 Typeahead#getDomReadyScript(TypeaheadConfig config).
Or getConfig() should be called only once in that method - and stored in a
local variable.



2015-03-05 10:34 GMT+01:00 Robert Gründler <notifications@github.com>:

**Comment by martin-g** [comment]
Fixed with #505
