### ISSUE TITLE
Documentation for DropZoneFileUpload

### ISSUE THREAD

**Issue by benplocek** [l0rdn1kk0n/wicket-bootstrap#521]
Or: What is the proper way to override the preview-template for DropZoneFileUpload?

It's really cool that dropzone.js is part of the wicket-extensions project, but the documentation for it is mostly missing - at least I couldn't find one.

Currently I want to find out how to override the preview-template for image previews from source. I already found out, that I can set config.withPreviewTemplate() but don't know what to pass here. I also saw that the original template is defined within DropZoneFileUpload.html but can I override this HTML?

I can contribute a wiki page or some other documentation for using DropZoneFileUpload. Please just tell me where to put it and answer my question from above :-)

**Comment by martin-g** [comment]
@klopfdreh Ping!

**Comment by klopfdreh** [comment]
The extensions of wicket bootstrap are documented only by examples as far as I could see - if you could tell more about the requirement / the default usage of it in DropZone and why it is needed - we can find a way to integrate it.

@martin-g Is there a good place to start a wiki for bootstrap extensions?

**Comment by benplocek** [comment]
@klopfdreh I wanted to add a success icon like the one in the official dropzone.js-demo on http://www.dropzonejs.com/. Any other idea how to achieve this?

**Comment by klopfdreh** [comment]
I am going to check it out soon - maybe you can add something with the ajax request target to Show that the Upload is completed successful until I implemented the functionality - or completely replace the Upload Panel for example

**Comment by benplocek** [comment]
Just found out that I can pass the template using single _and_ double quotes:

    .withPreviewTemplate("'<div class=\"file-row\"><span class=\"preview\"><img data-dz-thumbnail /></span></div>'")

With this, the defined HTML is being inserted inside the upload-container when dropping an image, but it's _this_ HTML only, so the <img>-component is not being replaced or populated with the real image.

**Comment by benplocek** [comment]
Found the problem and I'd say it's a bug: In line 24 of [dropzone_init.js](https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/fileUpload/js/dropzone_init.js#L24) you are trying to set `onclick` for an element with the class `.start`, but in my template, there was no element with `class="start"`.

When I use the following template, it's working:

    .withPreviewTemplate("'<div class=\"dz-preview\"><p class=\"name\" data-dz-name></p><img data-dz-thumbnail /><input type=\"hidden\" class=\"start\"/></div>'")

**Comment by klopfdreh** [comment]
I think it is no bug, because in the default template there is an element with .start class. 

https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/master/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/fileUpload/DropZoneFileUpload.html#L53

If you replace the template you have to ensure that there is an element that contains the start class, like you did. Maybe we can make a hint in the javadoc of widthPreviewTemplate. So that it is more clear what to do if replacing the template. It is hard to make everything configurable like in libraries which provides a bunch of functionality.

So if I would make a placeholder of the class - the user has to set the class and the template. If the class is not configurable the user has to write a template which fits to the class used in the javascript, which I think is the better way, if documented right.

What do you think?

**Comment by klopfdreh** [comment]
@benplocek Ping!

**Comment by klopfdreh** [comment]
I added some javadoc to provide those background information.

@martin-g - I think this issue can be closed. :-)
