### ISSUE TITLE
Add integration with Bootstrap-Markdown

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-bootstrap#589]
http://www.codingdrama.com/bootstrap-markdown/

It also supports integration with DropZone!

**Comment by dashorst** [comment]
Cool plugin! I'll try to integrate it into my current project (conference planner with markdown text for the CMS part)

I suspect in order to make integrations with other bootstrap plugins, the resource reference setup needs to be refactored. Currently I don't see a way to add a dependency on the de.agilecoders bootstrap from webjars to prevent multiple includes and wrongly ordered includes.

**Comment by martin-g** [comment]
Enjoy!

About the dependency management: a quickstart that shows the problem or a PR is welcome!

**Comment by dashorst** [comment]
Arg... I was being daft... the BootstrapSettings class provides everything I need.

**Comment by martin-g** [comment]
Cool!
