### ISSUE TITLE
wicket-bootstrap-samples v0.10.6 doesn't exist

### ISSUE THREAD

**Issue by frozhen** [l0rdn1kk0n/wicket-bootstrap#632]
I can only find v0.10.4 here:
https://mvnrepository.com/artifact/de.agilecoders.wicket/wicket-bootstrap-samples

**Comment by martin-g** [comment]
This is intentional: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/wicket-7.x/bootstrap-samples/pom.xml#L224
Since some time we decided to not upload samples modules to Maven Central because:
1) well, they are just samples. They are packed in a .war file and user applications don't use them as dependencies
2) it takes more time to make a release if we upload big .war files

**Comment by martin-g** [comment]
You can checkout the tag you need and build it locally.
