### ISSUE TITLE
Wicket bootstrap sample is not working properly out of the box

### ISSUE THREAD

**Issue by alcaTed-dev** [l0rdn1kk0n/wicket-bootstrap#657]
After downloading the sample and deploying it on weblogic, I see in the console of chrome that there are errors.
jquery-migrate-1.3.0.js:23 JQMIGRATE: Logging is active
components:2862 GET http://localhost:7001/demo/wicket/resource/de.agilecoders.wicket.webjars.re….WebjarsJavaScriptResourceReference/webjars/bootstrap/null/js/bootstrap.js 
application.js:18 Uncaught TypeError: $(...).affix is not a function
    at HTMLDocument.<anonymous> (application.js:18)
    at fire (jquery-1.12.4.js:3232)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.js:3362)
    at Function.ready (jquery-1.12.4.js:3582)
    at HTMLDocument.completed (jquery-1.12.4.js:3617)
(anonymous) @ application.js:18
fire @ jquery-1.12.4.js:3232
fireWith @ jquery-1.12.4.js:3362
ready @ jquery-1.12.4.js:3582
completed @ jquery-1.12.4.js:3617

**Comment by martin-g** [comment]
I'm sorry but WebLogic is not supported.
It is a commercial web server to which I have no access, so I cannot debug and improve the library. I guess the problem is with https://github.com/l0rdn1kk0n/wicket-webjars.
If you find the problem and you have a solution that doesn't break the other web servers then I'd be happy to apply it!

P.S. Same applies to WebSphere.
